on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'GuildRecruiter.code-workspace'

jobs:
  standalone_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine if Tag Push
        id: tagcheck
        run: echo "::set-output name=tag::$(if [ ${{ github.event.ref_type }} == 'tag' ]; then echo 'true'; else echo 'false'; fi)"

      - name: Ensure CHANGELOG.md is included
        if: steps.tagcheck.outputs.tag == 'true'
        run: |
          cp CHANGELOG.md .pkgmeta

      - name: Package
        if: steps.tagcheck.outputs.tag == 'true'
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
