name: "Release AddOn"

on:
  push:
    branches:
      - 'main'
    tags:
      - "-**-alpha**"
      - "-**-beta**"

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}

jobs:
standalone_release:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@v2
      with:
        pkgmeta: package_gr.pkgmeta
        args: -p 882061
        